# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1526d9bf50501d3dc6433adf49f5e1a5d3f3cdfbce8345b758007127d2709a9d72e399f864326aa6ac57cf7f273d65f3728a5a9789360b5d0533db2104f7fb5f

test:
  secret_key_base: 760c078424823264f405d1a56ce6add0392f8445cc1212037674cd434dffe139be9ca702c97c701121fb709d1722f7b868fd3ff8f4c82797a79809530f1e0373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
